/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import {
  useGLTF,
  useAnimations,
  Cone,
  GradientTexture,
} from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/mt-rainier-raised-bake-v2.glb"
  );
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  useEffect(() => {
    actions?.action.play();
  });

  return (
    <group
      // rotation={[0.2, 0.5, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      <group name="Scene">
        <group
          name="GOOGLE_SAT_WM"
          position={[2067.86, 0, -1239.92]}
          scale={[88055.45, 1, 88055.45]}
        />
        <group
          name="H_design"
          position={[2.53, 8.66, -8.73]}
          rotation={[0.92, 0.25, -1.24]}
          scale={[0.53, 0.53, 0.53]}
        >
          <mesh
            name="H_design_1"
            geometry={nodes.H_design_1.geometry}
            material={materials.goldmesh}
          />
          <mesh
            name="H_design_2"
            geometry={nodes.H_design_2.geometry}
            material={materials.solararray}
          />
          <mesh
            name="H_design_3"
            geometry={nodes.H_design_3.geometry}
            material={materials.Al}
          />
          <mesh
            name="H_design_4"
            geometry={nodes.H_design_4.geometry}
            material={materials.CANNISTER}
          />
          <mesh
            name="H_design_5"
            geometry={nodes.H_design_5.geometry}
            material={materials["CARBON FIBER"]}
          />
          <mesh
            name="H_design_6"
            geometry={nodes.H_design_6.geometry}
            material={materials["SOLAR ARRAY HINGE"]}
          />
          <mesh
            name="H_design_7"
            geometry={nodes.H_design_7.geometry}
            material={materials.Tapes}
          />
          <mesh
            name="H_design_8"
            geometry={nodes.H_design_8.geometry}
            material={materials.Ultem}
          />
          <mesh
            name="H_design_9"
            geometry={nodes.H_design_9.geometry}
            material={materials.Copper}
          />
          <mesh
            name="H_design_10"
            geometry={nodes.H_design_10.geometry}
            material={materials.Subreflector}
          />
          {/* <mesh
            name="Cone002"
            geometry={nodes.Cone002.geometry}
            material={nodes.Cone002.material}
            position={[-0.3, 0.21, 10.43]}
            rotation={[-1.68, -1.21, -0.09]}
            scale={[1.96, 2.69, 2.42]}
          /> */}
          <Cone
            args={[2, 20]}
            position={[0, 0, 12]}
            rotation={[-1.52, 1.61, -0.06]}
          >
            <meshBasicMaterial opacity={0.9} transparent>
              {" "}
              <GradientTexture
                stops={[0, 0.5, 1]} // As many stops as you want
                colors={["aqua", "aqua", "transparent"]} // Colors need to match the number of stops
                size={1024}
              />
            </meshBasicMaterial>
          </Cone>
        </group>
        <group
          name="EXPORT_GOOGLE_SAT_WM"
          position={[1.18, 0.64, 0.06]}
          scale={0.2}
        >
          <mesh
            name="EXPORT_GOOGLE_SAT_WM_1"
            geometry={nodes.EXPORT_GOOGLE_SAT_WM_1.geometry}
            material={materials["Material.001"]}
            material-roughness={1}
          />

          <mesh
            name="EXPORT_GOOGLE_SAT_WM_2"
            geometry={nodes.EXPORT_GOOGLE_SAT_WM_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mt-rainier-raised-bake-v2.glb");
